# Generated by Django 2.0.7 on 2020-10-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepgoal',
            name='parentUser',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
