# Generated by Django 2.0.7 on 2020-10-26 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_goals', '0002_auto_20201023_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisegoal',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
