# Generated by Django 2.0.7 on 2020-10-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_goals', '0003_exercisegoal_createddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisegoal',
            old_name='description',
            new_name='goal',
        ),
    ]
