# Generated by Django 2.0.7 on 2020-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('age', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True, choices=[(53, '4\'5"'), (54, '4\'6"'), (55, '4\'7"'), (56, '4\'8"'), (57, '4\'9"'), (58, '4\'10"'), (59, '4\'11"'), (60, '5\'0"'), (61, '5\'1"'), (62, '5\'2"'), (63, '5\'3"'), (64, '5\'4"'), (65, '5\'5"'), (66, '5\'6"'), (67, '5\'7"'), (68, '5\'8"'), (69, '5\'9"'), (70, '5\'10"'), (71, '5\'11"'), (72, '6\'0"'), (73, '6\'1"'), (74, '6\'2"'), (75, '6\'3"'), (76, '6\'4"'), (77, '6\'5"'), (78, '6\'6"'), (79, '6\'7"'), (80, '6\'8"')], default=65)),
                ('weight', models.IntegerField(blank=True, default=150)),
                ('avg_sleep', models.IntegerField(blank=True, default=8)),
                ('exercise_level', models.IntegerField(blank=True, choices=[(0, 'Barely Exercise'), (1, 'Exercise Once In a While'), (2, 'Exercise Once a Week'), (3, 'Exercise 2-3 Times a Week'), (4, 'Exercise Daily')], default=2)),
            ],
        ),
    ]
