# Generated by Django 3.1.2 on 2020-11-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20201026_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.IntegerField(choices=[(0, 'Exercise'), (0, 'Appointment'), (0, 'Nutrition'), (0, 'Sleep')], default=0)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
