# Generated by Django 3.1.2 on 2020-11-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
