# Generated by Django 3.1.2 on 2020-11-10 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_delete_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.IntegerField(choices=[(0, 'Exercise'), (1, 'Nutrition'), (2, 'Sleep'), (3, 'Appointment')], default=0)),
                ('date', models.DateTimeField(choices=[(datetime.datetime(2020, 11, 24, 3, 33, 15, 949547), '2 weeks'), (datetime.datetime(2020, 11, 11, 3, 33, 15, 949523), 'tomorrow'), (datetime.datetime(2020, 12, 10, 3, 33, 15, 949549), '1 month'), (datetime.datetime(2020, 11, 17, 3, 33, 15, 949545), '1 week')], default=profiles.models.tomorrow)),
                ('description', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
