# Generated by Django 3.1.2 on 2020-11-10 18:01

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_usergoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 11, 18, 1, 56, 412224), 'tomorrow'), (datetime.datetime(2020, 11, 17, 18, 1, 56, 412242), '1 week'), (datetime.datetime(2020, 12, 10, 18, 1, 56, 412245), '1 month'), (datetime.datetime(2020, 11, 24, 18, 1, 56, 412244), '2 weeks')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (1, 'Nutrition'), (3, 'Appointment'), (0, 'Exercise')], default=0),
        ),
    ]
