# Generated by Django 3.1.2 on 2020-11-10 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201110_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.IntegerField(choices=[(1, 'Nutrition'), (0, 'Exercise'), (3, 'Appointment'), (2, 'Sleep')], default=0)),
                ('date', models.DateTimeField(choices=[(datetime.datetime(2020, 11, 24, 18, 5, 14, 190648), '2 weeks'), (datetime.datetime(2020, 12, 10, 18, 5, 14, 190650), '1 month'), (datetime.datetime(2020, 11, 11, 18, 5, 14, 190633), 'tomorrow'), (datetime.datetime(2020, 11, 17, 18, 5, 14, 190647), '1 week')], default=profiles.models.tomorrow)),
                ('description', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
