# Generated by Django 3.1.2 on 2020-11-10 18:15

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201110_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 17, 18, 15, 3, 429293), '1 week'), (datetime.datetime(2020, 12, 10, 18, 15, 3, 429296), '1 month'), (datetime.datetime(2020, 11, 11, 18, 15, 3, 429275), 'tomorrow'), (datetime.datetime(2020, 11, 24, 18, 15, 3, 429295), '2 weeks')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (1, 'Nutrition'), (0, 'Exercise'), (2, 'Sleep')], default=0),
        ),
    ]
