# Generated by Django 3.1.2 on 2020-11-10 19:43

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20201110_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 10, 19, 43, 44, 450386), '1 month'), (datetime.datetime(2020, 11, 17, 19, 43, 44, 450382), '1 week'), (datetime.datetime(2020, 11, 24, 19, 43, 44, 450384), '2 weeks'), (datetime.datetime(2020, 11, 11, 19, 43, 44, 450360), 'tomorrow')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(0, 'Exercise'), (2, 'Sleep'), (3, 'Appointment'), (1, 'Nutrition')], default=0),
        ),
    ]
