# Generated by Django 3.1.2 on 2020-11-11 19:03

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20201110_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 25, 19, 3, 27, 139911), '2 weeks'), (datetime.datetime(2020, 12, 11, 19, 3, 27, 139913), '1 month'), (datetime.datetime(2020, 11, 12, 19, 3, 27, 139896), 'tomorrow'), (datetime.datetime(2020, 11, 18, 19, 3, 27, 139910), '1 week')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition'), (3, 'Appointment')], default=0),
        ),
    ]
