# Generated by Django 3.1.2 on 2020-11-11 19:05

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201111_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 25, 19, 5, 16, 105824), '2 weeks'), (datetime.datetime(2020, 11, 18, 19, 5, 16, 105823), '1 week'), (datetime.datetime(2020, 12, 11, 19, 5, 16, 105825), '1 month'), (datetime.datetime(2020, 11, 12, 19, 5, 16, 105810), 'tomorrow')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (0, 'Exercise'), (2, 'Sleep'), (1, 'Nutrition')], default=0),
        ),
    ]
