# Generated by Django 3.1.2 on 2020-11-11 19:07

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20201111_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 11, 19, 7, 5, 750057), '1 month'), (datetime.datetime(2020, 11, 25, 19, 7, 5, 750056), '2 weeks'), (datetime.datetime(2020, 11, 12, 19, 7, 5, 750041), 'tomorrow'), (datetime.datetime(2020, 11, 18, 19, 7, 5, 750054), '1 week')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition'), (3, 'Appointment')], default=0),
        ),
    ]
