# Generated by Django 3.1.2 on 2020-11-11 19:10

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20201111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 11, 19, 10, 6, 243094), '1 month'), (datetime.datetime(2020, 11, 25, 19, 10, 6, 243092), '2 weeks'), (datetime.datetime(2020, 11, 18, 19, 10, 6, 243091), '1 week'), (datetime.datetime(2020, 11, 12, 19, 10, 6, 243076), 'tomorrow')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(1, 'Nutrition'), (0, 'Exercise'), (3, 'Appointment'), (2, 'Sleep')], default=0),
        ),
    ]
