# Generated by Django 3.1.2 on 2020-11-17 01:56

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20201111_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 24, 1, 56, 55, 769854), '1 week'), (datetime.datetime(2020, 11, 18, 1, 56, 55, 769838), 'tomorrow'), (datetime.datetime(2020, 12, 1, 1, 56, 55, 769856), '2 weeks'), (datetime.datetime(2020, 12, 17, 1, 56, 55, 769857), '1 month')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (0, 'Exercise'), (1, 'Nutrition'), (2, 'Sleep')], default=0),
        ),
    ]
