# Generated by Django 3.1.2 on 2020-11-18 01:16

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20201117_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 19, 1, 16, 15, 457986), 'tomorrow'), (datetime.datetime(2020, 11, 25, 1, 16, 15, 458001), '1 week'), (datetime.datetime(2020, 12, 18, 1, 16, 15, 458004), '1 month'), (datetime.datetime(2020, 12, 2, 1, 16, 15, 458003), '2 weeks')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (1, 'Nutrition'), (0, 'Exercise'), (2, 'Sleep')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
