# Generated by Django 3.1.2 on 2020-12-01 16:08

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20201118_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 31, 16, 8, 49, 826315), '1 month'), (datetime.datetime(2020, 12, 2, 16, 8, 49, 826298), 'tomorrow'), (datetime.datetime(2020, 12, 8, 16, 8, 49, 826312), '1 week'), (datetime.datetime(2020, 12, 15, 16, 8, 49, 826314), '2 weeks')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition')], default=0),
        ),
    ]
