# Generated by Django 3.1.2 on 2020-12-01 16:55

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20201201_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appointments_complete',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise_complete',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nutrition_complete',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_complete',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 15, 16, 54, 15, 122820), '2 weeks'), (datetime.datetime(2020, 12, 8, 16, 54, 15, 122818), '1 week'), (datetime.datetime(2020, 12, 31, 16, 54, 15, 122821), '1 month'), (datetime.datetime(2020, 12, 2, 16, 54, 15, 122805), 'tomorrow')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(0, 'Exercise'), (3, 'Appointment'), (2, 'Sleep'), (1, 'Nutrition')], default=0),
        ),
    ]
