# Generated by Django 3.1.2 on 2020-12-01 17:25

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20201201_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='appointments_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exercise_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nutrition_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleep_complete',
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 8, 17, 25, 33, 734686), '1 week'), (datetime.datetime(2020, 12, 31, 17, 25, 33, 734689), '1 month'), (datetime.datetime(2020, 12, 2, 17, 25, 33, 734670), 'tomorrow'), (datetime.datetime(2020, 12, 15, 17, 25, 33, 734688), '2 weeks')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition')], default=0),
        ),
    ]
