# Generated by Django 3.1.4 on 2020-12-03 18:18

import datetime
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20201201_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='a_goals_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_goals_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_goals_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='s_goals_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2021, 1, 2, 18, 18, 52, 517890), '1 month'), (datetime.datetime(2020, 12, 4, 18, 18, 52, 517867), 'tomorrow'), (datetime.datetime(2020, 12, 17, 18, 18, 52, 517889), '2 weeks'), (datetime.datetime(2020, 12, 10, 18, 18, 52, 517887), '1 week')], default=profiles.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition'), (3, 'Appointment')], default=0),
        ),
    ]
