# Generated by Django 3.1.2 on 2020-11-09 19:28

from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20201109_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(1, 'Nutrition'), (3, 'Appointment'), (0, 'Exercise'), (2, 'Sleep')], default=0),
        ),
    ]
