# Generated by Django 3.1.2 on 2020-11-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20201109_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(1, 'Nutrition'), (2, 'Sleep'), (0, 'Exercise'), (3, 'Appointment')], default=0),
        ),
    ]
