# Generated by Django 3.1.2 on 2020-11-09 19:45

import datetime
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20201109_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 23, 19, 45, 8, 83013), '2 weeks'), (datetime.datetime(2020, 11, 10, 19, 45, 8, 82998), 'tomorrow'), (datetime.datetime(2020, 12, 9, 19, 45, 8, 83014), '1 month'), (datetime.datetime(2020, 11, 16, 19, 45, 8, 83012), '1 week')], default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (1, 'Nutrition'), (3, 'Appointment'), (0, 'Exercise')], default=0),
        ),
    ]
