# Generated by Django 3.1.2 on 2020-11-09 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0011_auto_20201109_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 9, 19, 47, 32, 983284), '1 month'), (datetime.datetime(2020, 11, 16, 19, 47, 32, 983281), '1 week'), (datetime.datetime(2020, 11, 23, 19, 47, 32, 983283), '2 weeks'), (datetime.datetime(2020, 11, 10, 19, 47, 32, 983252), 'tomorrow')], default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (1, 'Nutrition'), (0, 'Exercise')], default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
