# Generated by Django 3.1.2 on 2020-11-09 21:35

import datetime
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20201109_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 10, 21, 35, 50, 434603), 'tomorrow'), (datetime.datetime(2020, 11, 16, 21, 35, 50, 434625), '1 week'), (datetime.datetime(2020, 12, 9, 21, 35, 50, 434628), '1 month'), (datetime.datetime(2020, 11, 23, 21, 35, 50, 434627), '2 weeks')], default=goals.models.tomorrow),
        ),
    ]
