# Generated by Django 3.1.2 on 2020-11-09 21:57

import datetime
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_auto_20201109_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 12, 9, 21, 57, 38, 511796), '1 month'), (datetime.datetime(2020, 11, 10, 21, 57, 38, 511763), 'tomorrow'), (datetime.datetime(2020, 11, 23, 21, 57, 38, 511794), '2 weeks'), (datetime.datetime(2020, 11, 16, 21, 57, 38, 511791), '1 week')], default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (0, 'Exercise'), (1, 'Nutrition'), (2, 'Sleep')], default=0),
        ),
    ]
