# Generated by Django 3.1.2 on 2020-11-09 22:00

import datetime
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_auto_20201109_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(choices=[(datetime.datetime(2020, 11, 10, 22, 0, 24, 449642), 'tomorrow'), (datetime.datetime(2020, 11, 23, 22, 0, 24, 449658), '2 weeks'), (datetime.datetime(2020, 12, 9, 22, 0, 24, 449659), '1 month'), (datetime.datetime(2020, 11, 16, 22, 0, 24, 449656), '1 week')], default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition'), (3, 'Appointment')], default=0),
        ),
    ]
