# Generated by Django 3.1.2 on 2020-11-10 03:33

from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_auto_20201109_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(default=goals.models.tomorrow),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(0, 'Exercise'), (1, 'Nutrition'), (2, 'Sleep'), (3, 'Appointment')], default=0),
        ),
    ]
