# Generated by Django 3.1.2 on 2020-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_auto_20201110_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (1, 'Nutrition'), (0, 'Exercise')], default=0),
        ),
    ]
