# Generated by Django 3.1.2 on 2020-11-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_auto_20201110_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(0, 'Exercise'), (2, 'Sleep'), (3, 'Appointment'), (1, 'Nutrition')], default=0),
        ),
    ]
