# Generated by Django 3.1.2 on 2020-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_auto_20201111_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (0, 'Exercise'), (2, 'Sleep'), (1, 'Nutrition')], default=0),
        ),
    ]
