# Generated by Django 3.1.2 on 2020-11-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0024_auto_20201111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(1, 'Nutrition'), (0, 'Exercise'), (3, 'Appointment'), (2, 'Sleep')], default=0),
        ),
    ]
