# Generated by Django 3.1.2 on 2020-11-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0027_auto_20201117_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (1, 'Nutrition'), (0, 'Exercise'), (2, 'Sleep')], default=0),
        ),
    ]
