# Generated by Django 3.1.2 on 2020-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0028_auto_20201118_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition')], default=0),
        ),
    ]
