# Generated by Django 3.1.2 on 2020-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0030_auto_20201201_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.IntegerField(choices=[(3, 'Appointment'), (2, 'Sleep'), (0, 'Exercise'), (1, 'Nutrition')], default=0),
        ),
    ]
